services:
  ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: re_ai
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    networks:
      - default
      - re_shared

networks:
  re_shared:
    external: true
